# Font
font_family                   Hack Nerd Font Mono
bold_font                     Hack Nerd Font Mono Bold
italic_font                   Hack Nerd Font Mono Italic
bold_italic_font              Hack Nerd Font Mono Bold Italic
font_size                     11.0
disable_ligatures             cursor
text_composition_strategy     platform
undercurl_style               thin-dense

# Window
background_opacity            0.9
dynamic_background_opacity    no
background_blur               0
confirm_os_window_close       0
remember_window_size          no
initial_window_width          110c
initial_window_height         30c
window_padding_width          5
single_window_padding_width   5
window_border_width           1pt
active_border_color           #3d59a1
inactive_border_color         #101014
bell_border_color             #e0af68
window_margin_width           0
hide_window_decorations       yes
draw_minimal_borders          yes
window_resize_step_cells      2
window_resize_step_lines      2
placement_strategy            center
inactive_text_alpha           0.9

# Shell integration
shell_integration             no-cursor

# Cursor
cursor                        #a9b1d6
cursor_text_color             background
cursor_shape                  block
cursor_shape_unfocused        hollow
cursor_blink_interval         0.5 ease-in-out
cursor_stop_blinking_after    15.0
cursor_trail                  1
cursor_trail_decay            0.1 0.4
cursor_trail_start_threshold  2

# Scrolling
scrollbar                     never
scrollback_lines              10000
wheel_scroll_min_lines        1
scrollback_pager              less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

# Mouse
mouse_hide_wait               3.0
url_color                     #9ece6a
url_style                     curly
detect_urls                   yes
copy_on_select                no
strip_trailing_spaces         smart
focus_follows_mouse           yes

# Performance
repaint_delay                 10
input_delay                   3
sync_to_monitor               yes

# Bell
enable_audio_bell             no
visual_bell_duration          0.1
visual_bell_color             #9ece6a
window_alert_on_bell          yes
bell_on_tab                   "● "
command_on_bell               none

# Tab bar
tab_bar_style                 hidden

# Colors
foreground                    #a9b1d6
background                    #1a1b26

selection_foreground          none
selection_background          #28344a

# Black
color0                        #32344a
color8                        #444b6a

# Red
color1                        #f7768e
color9                        #ff7a93

# Green
color2                        #9ece6a
color10                       #b9f27c

# Yellow
color3                        #e0af68
color11                       #ff9e64

# Blue
color4                        #7aa2f7
color12                       #7da6ff

# Magenta
color5                        #ad8ee6
color13                       #bb9af7

# Cyan
color6                        #449dab
color14                       #0db9d7

# White
color7                        #787c99
color15                       #acb0d0

