### Autostart

# Notification daemon
exec dunst

# Pipewire
# exec pipewire
# exec pipewire-pulse
# exec wireplumber

# Hide coursor after inactivity
seat * hide_cursor 5000

# Hide cursor when typing
seat * hide_cursor when-typing enable
