### Graphical settings

# Background
output * bg $wallpaper fill

# Main output
# output HDMI-A-1 resolution 1920x1080 position 1920,0

# Borders
default_border pixel 2
 client.focused #0db9d7 #000000 #0db9d7 #0db9d7 #0db9d7
 client.unfocused #449dab #000000 #449dab #449dab #449dab
 client.background #000000
gaps inner 5

# Window effects
corner_radius 10
blur enable
default_dim_inactive 0.15

# Layer effects
layer_effects "rofi" {
  blur enable;
}
layer_effects "dunst" {
  blur enable;
}
