### Variables

# Logo key. Use Mod1 for Alt
input * xkb_rules evdev
set $mod Mod4

# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

# Preferred apps
set $terminal kitty
set $editor nvim
set $code code-oss
set $taskmanager btop
set $filemanager thunar
set $browser firefox

# Menu
set $menu "rofi -show drun"

# Wallpaper
set $wallpaper ~/Pictures/Wallpapers/freebsd_tokyonight.png

# Lockscreen configuration
set $screenlock "swaylock --config ~/.config/swaylock/config"
