# Wayland default floats
for_window [app_id="pavucontrol"] floating enable
for_window [app_id="mpv"] floating enable
for_window [app_id="mpv"] resize set 960 540
for_window [app_id="mpv"] border pixel 0
for_window [app_id="firefox" title="Pushbullet"] floating enable
for_window [app_id="firefox" title="Firefox — Sharing Indicator"] floating enable
for_window [app_id="firefox" title="Picture-in-Picture"] floating enable
for_window [app_id="firefox" title="Pushbullet – Mozilla Firefox"] floating enable
for_window [app_id="firefox" title="About Mozilla Firefox"] floating enable
